name: Team awesome's approval workflow
on: pull_request_review
jobs:
    labelWhenApproved:
        runs-on: ubutu-latest
        steps:
          uses: pullreminders/label-when-approved-action
            env:
              APPROVALS: "1"
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              ADD_LABEL: "Approved"